import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        {children}
       <Toaster 
          position="top-center" 
          toastOptions={{
            // Applying your site's "Big & Bold" aesthetic
            className: "rounded-2xl border-2 border-slate-800 bg-[#0B1120] text-white p-4 shadow-2xl",
            descriptionClassName: "text-slate-400 font-medium",
            actionButtonStyle: {
              backgroundColor: '#4f46e5', // indigo-600
              borderRadius: '0.75rem',
              fontWeight: '900',
              padding: '0.5rem 1rem',
            },
            cancelButtonStyle: {
              backgroundColor: 'transparent',
              color: '#94a3b8', // slate-400
              fontWeight: '700',
            },
          }}
        />
      </body>
    </html>
  );
}
